In [13]:
import numpy as np
myarr=np.array([[1,2,3,4],[5,6,7,8]],dtype=np.int64)
print(myarr)
print(myarr.size)
print(myarr[1,0])
myarr[1,0]=456
print(myarr)

arr=np.array([(1,2),(3,4)])
print(arr)
arr[0,0]=0
print(arr)
print(arr.size)

zeros=np.zeros((2,5))
print(zeros)
print(zeros.shape)

[[1 2 3 4]
 [5 6 7 8]]
8
5
[[  1   2   3   4]
 [456   6   7   8]]
[[1 2]
 [3 4]]
[[0 2]
 [3 4]]
4
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(2, 5)


In [16]:
rng=np.arange(15)
print(rng)

linspace=np.linspace(1,10,10)
print(linspace)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [19]:
emp=np.empty((2,3))
print(emp)

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
ide=np.identity(5)
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
ide.shape

(5, 5)

In [23]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [25]:
arr.reshape(9,11)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
       [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87],
       [88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [27]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr.shape

(99,)

**NUMPY AXIS**

In [30]:
x=[[1,2,3],[4,5,6],[7,1,0]]
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [31]:
ar.sum(axis=0)

array([12,  8,  9])

In [32]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [33]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [35]:
iterator=ar.flat

In [37]:
iterator=ar.flat
for item in iterator:
    print(item)

1
2
3
4
5
6
7
1
0


In [38]:
ar.ndim

2

In [39]:
ar.size

9

In [40]:
ar.nbytes

36

In [51]:
one = np.array([[1,2,3],[49,5,-9]])
print(one.argmax())
print(one.argmin())

3
5


In [52]:
one.argsort()

array([[0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [53]:
unsorted=np.array([23,2,0,-9,1])
unsorted.argsort()

array([3, 2, 4, 1, 0], dtype=int64)

In [54]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [55]:
ar.argmax()

6

In [56]:
ar.argmin()

8

In [57]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [58]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [59]:
ar.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [60]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [3]:
import numpy as np
ar=np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [64]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [66]:
ar1=np.array([[-7, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

ar2=ar+ar1
ar2

array([[-6,  4,  6],
       [ 8, 10, 12],
       [14,  2,  0]])

In [67]:
ar*ar1

array([[-7,  4,  9],
       [16, 25, 36],
       [49,  1,  0]])

In [68]:
np.sqrt(ar2)

C:\Users\Hp\AppData\Local\Temp\ipykernel_17912\1747013956.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(ar2)


array([[       nan, 2.        , 2.44948974],
       [2.82842712, 3.16227766, 3.46410162],
       [3.74165739, 1.41421356, 0.        ]])

In [69]:
ar.sum()

29

In [71]:
print(ar)
np.where(ar>5)

[[1 2 3]
 [4 5 6]
 [7 1 0]]


(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [72]:
np.count_nonzero(ar)

8

In [75]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

WHY ARRAYS ARE BETTER THAN LISTS IN CONSERVING MEMORY

In [79]:
import sys
py_li=[0,4,55,2]
np_ar=np.array(py_li)
sys.getsizeof(1)*len(py_li)



112

In [78]:
np_ar.itemsize * np_ar.size

16

In [80]:
np_ar.tolist()

[0, 4, 55, 2]